### ISSUE TITLE
Mod version Outdated

### ISSUE THREAD

**Issue by SteamDoge9000** [jrbudda/Vivecraft_112#104]
When i atempted to update the installed forge verson via reinstall

i get an error that is as the following: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerCore-1.12.2-2.0.4.4.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/9/19 6:52 PM
Description: Initializing game

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:34)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_202_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:810)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:636)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:34)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_202_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:810)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:636)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3871178064 bytes (3691 MB) / 4250402816 bytes (4053 MB) up to 4250402816 bytes (4053 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 Optifine OptiFine_1.12.2_HD_U_E3 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                             | Signature                                |
	|:----- |:--------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft             | 1.12.2            | minecraft.jar                                      | None                                     |
	| LC    | mcp                   | 9.42              | minecraft.jar                                      | None                                     |
	| LC    | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                 | 14.23.5.2815      | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | techguns_core         | 1.12.2-1.0        | minecraft.jar                                      | None                                     |
	| LC    | mercurius_updater     | 1.0               | MercuriusUpdater-1.12.2.jar                        | None                                     |
	| LC    | advancedcombat        | 1.1.2             | advancedcombat-1.1.2-[1.12].jar                    | None                                     |
	| LC    | akashictome           | 1.2-12            | AkashicTome-1.2-12.jar                             | None                                     |
	| LC    | applecore             | 3.2.0             | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LC    | appleskin             | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LC    | autoreglib            | 1.3-26            | AutoRegLib-1.3-26.jar                              | None                                     |
	| LC    | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | guideapi              | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LC    | bloodmagic            | 1.12.2-2.4.0-102  | BloodMagic-1.12.2-2.4.0-102.jar                    | None                                     |
	| LC    | bloodarsenal          | 1.12.2-2.1.0-25   | BloodArsenal-1.12.2-2.1.0-26.jar                   | None                                     |
	| LC    | bookshelf             | 2.3.577           | Bookshelf-1.12.2-2.3.577.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | codechickenlib        | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux          | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | brandonscore          | 2.4.10            | BrandonsCore-1.12.2-2.4.10.198-universal.jar       | None                                     |
	| LC    | chameleon             | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LC    | ctm                   | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LC    | chisel                | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LC    | waila                 | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | darkutils             | 1.8.223           | DarkUtils-1.12.2-1.8.223.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | deepmoblearning       | 1.12.2-2.5.0      | deepmoblearning-1.12.2-2.5.0-universal.jar         | None                                     |
	| LC    | draconicevolution     | 2.3.21            | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |
	| LC    | dummycore             | 2.4.112.5.        | DummyCoreUnofficial-2.4.112.5.jar                  | None                                     |
	| LC    | ic2                   | 2.8.109-ex112     | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | thaumcraft            | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LC    | emt                   | B_EMT3.4          | EMT-R_EMT10.9fix.jar                               | None                                     |
	| LC    | extrautils2           | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | hammercore            | 2.0.4.4           | HammerCore-1.12.2-2.0.4.4.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| L     | planarartifice        | 0.13              | planarartifice-0.13.jar                            | None                                     |
	| L     | flammpfeil.slashblade | mc1.12-r20        | SlashBlade-mc1.12-r20.jar                          | None                                     |
	| L     | storagedrawers        | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| L     | techguns              | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.1.jar                 | None                                     |
	| L     | thaumcraftnoresearch  | 1.0               | ThaumcraftNoResearch-1.0.jar                       | None                                     |
	| L     | tg                    | 0.1.5.0           | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar           | None                                     |
	| L     | thaumadditions        | 13r               | ThaumicAdditions-1.12.2-13r.jar                    | None                                     |
	| L     | thaumicbases          | 3.3.310.5r        | thaumicbases-3.3.345.6r.jar                        | None                                     |
	| L     | thaumicbrewing        | 1.0.2             | thaumicbrewing-1.0.2.jar                           | None                                     |
	| L     | tcinventoryscan       | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| L     | thaumicrestoration    | 1.3.1             | ThaumicRestoration-1.3.1.jar                       | None                                     |
	| L     | thaumicwonders        | 1.2.0             | thaumicwonders-1.2.0.jar                           | None                                     |
	| L     | lastsmith             | @version@         | TLS-V1.2.6-MC1.12.2.jar                            | None                                     |
	| L     | wailaharvestability   | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| L     | wawla                 | 2.5.269           | Wawla-1.12.2-2.5.269.jar                           | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerCore-1.12.2-2.0.4.4.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  DummyCore.ASM.DCASMManager
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 138 names; 176 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @13r

	Launched Version: vivecraft-1.12.2-jrbudda-7-r12-forge
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft,fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

it appears as if the game will not accept versions of forge that are beyond forge-12.23.5.2796

**Comment by 13r** [comment]
Can u please stop mentioning me, i am getting email notifications every time and its very annoying.
Thank you.

**Comment by TheTrueForce** [comment]
So for reference, what happened here was not deliberate. There was some random bit in a copy-pasted log file that did that.
This is one reason why you should use something like pastebin for logs, instead of copy-pasting them. They are also a pain to read.

**Comment by SteamDoge9000** [comment]
sorry
