### ISSUE TITLE
Launching with Little Tiles causes crash on startup

### ISSUE THREAD

**Issue by ParapetCloud** [jrbudda/Vivecraft_112#141]
trying to launch vivecraft with forge 1.12.2 has a crash on startup when little tiles v1.5.0-pre198 is in the mods folder

> Unable to launch
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:156)
> 	... 6 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:152)
> 	... 6 more
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
> 	at net.minecraft.client.main.Main.main(Main.java:45)
> 	... 11 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 12 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.littletiles.LittleTilesTransformer@79d82f66 from coremod LittlePatchingLoader
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> 	... 14 more
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
> 	at org.objectweb.asm.Frame.a(Unknown Source)
> 	at org.objectweb.asm.Frame.a(Unknown Source)
> 	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
> 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
> 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
> 	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
> 	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:46)
> 	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:32)
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
> 	... 16 more

**Comment by Techjar** [comment]
That looks like an asm conflict. This mod does some pretty wacky stuff so who knows what's wrong.
