### ISSUE TITLE
How to add custom locomotion option?

### ISSUE THREAD

**Issue by topin89** [jrbudda/Vivecraft_112#15]
Short version:
I want to constantly poll shared memory and change walk direction and speed (relative to max speed) according to memory state, and optionally change walk/run mode and send jump event. What should I add to your code and where?

Some details:

There is a struct in shared memory with:
- forward direction (arbitrary angle, not initially linked with any particular in-game direction)
- forward speed (negative for backward, -1.0 .. 1.0)
- right sidespeed (negative for left, -1.0 .. 1.0)
- sync flag (says game that forward direction is where you look right now)
- jump flag
(This may be changed to just speed (0.0 .. 1.0) and direction in the future.)

There is a swig-generated library to access said struct.

There must be controllers' state polling loop somewhere in code.
There may be a preferred way to add such polling, processing and in-game event generation.
Please, help me with last two.

I already tried to control game via https://github.com/matzman666/OpenVR-InputEmulator with some modifications. All is good, except I can't change speed this way, and this is the key to more immersion.
So even changing speed relative to trigger axis value would help a lot.

Why I need it:
I'm currently working on a feet-based locomotion device, and results are promising, at least one man with high motion sickness (to a point that he can't read in a moving car) says that he don't feel sick. But for this to work game needs to change speed according to leg movement.
Can't say more until my employer registered some patents and copyrights, but our company will make and spread some videos eventually.

**Comment by jrbudda** [comment]
Vivecraft (at least 1.11+) has support in it for KATvr treadmills which provide similar inputs. I believe src/MovementInputFromOptions.java is where most of the work is done, or just follow around the Main.java 'katvr' boolean.

**Comment by topin89** [comment]
Thanks. I'll comment here when I solve my problem. Or when I need more help.

**Comment by topin89** [comment]
I need more help :(
I tried to compile Vivecraft 1.12.1 v3 from releases, since repo says it's impossible to build from it. I used manual from minecrift repo, except I copied `1.12.1.jar` and `mcp940.zip` in source folder beforehand.
I got this:

```C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3>install.bat --clean
Using base dir: C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3
Using mcp dir: C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3\mcp940 (use -m <mcp-dir> to change)
Preferred architecture: 64bit - preferring 64bit native extraction (use -a 32 or -a 64 to change)
NO Optifine merging
Cleaning...

WARNING:
The clean option will delete all folders created by MCP, including the
src folder which may contain changes you made to the code, along with any
saved worlds from the client or server.
Minecrift downloaded dependencies will also be removed and re-downloaded.
Patches will be left alone however.
If you really want to clean up, enter "Yes" Yes
Cleaning mcp dir...
Cleaning lib dir...
Cleaning patchsrc dir...
Removing idea project files...
Installing mcp...
Checking for mcp zip file: C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3\mcp940.zip
Patching mcp.cfg. Ignore "FAILED" hunks
patching file mcp.cfg
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 171.
1 out of 1 hunk FAILED -- saving rejects to file mcp.cfg.rej
Updating Start.java: copying C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3\mcppatches\Start.java to C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3\mcp940\conf\patches\Start.java

Downloading dependencies...
Updating json: copying installer\1.12.1.json to C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3\mcp940\jars\versions\1.12.1\1.12.1.json
Checking Optifine...
Downloading Optifine...
Downloading: OptiFine-1.12.1_HD_U_C5.jar
Downloading: patchy-1.1.jar
Downloading: oshi-core-1.1.jar
Downloading: jna-4.4.0.jar
Downloading: platform-3.4.0.jar
Downloading: icu4j-core-mojang-51.2.jar
Downloading: jopt-simple-5.0.3.jar
Downloading: codecjorbis-20101023.jar
Downloading: codecwav-20101023.jar
Downloading: libraryjavasound-20101123.jar
Downloading: librarylwjglopenal-20100824.jar
Downloading: soundsystem-20120107.jar
Downloading: netty-all-4.1.9.Final.jar
Downloading: guava-21.0.jar
Downloading: commons-lang3-3.5.jar
Downloading: commons-io-2.5.jar
Downloading: commons-codec-1.10.jar
Downloading: jinput-2.0.5.jar
Downloading: jutils-1.0.0.jar
Downloading: gson-2.8.0.jar
Downloading: authlib-1.5.25.jar
Downloading: realms-1.10.17.jar
Downloading: commons-compress-1.8.1.jar
Downloading: httpclient-4.3.3.jar
Downloading: commons-logging-1.1.3.jar
Downloading: httpcore-4.3.2.jar
Downloading: fastutil-7.1.0.jar
Downloading: log4j-api-2.8.1.jar
Downloading: log4j-core-2.8.1.jar
Downloading: lwjgl-2.9.4-nightly-20150209.jar
Downloading: lwjgl_util-2.9.4-nightly-20150209.jar
Downloading: lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
    Extracting native library OpenAL32.dll
    Extracting native library OpenAL64.dll
    Extracting native library lwjgl.dll
    Extracting native library lwjgl64.dll
File: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
Skipping due to rules
File: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
Skipping due to rules
File: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
Skipping due to rules
Downloading: jinput-platform-2.0.5-natives-windows.jar
    Extracting native library jinput-dx8.dll
    Extracting native library jinput-dx8_64.dll
    Extracting native library jinput-raw.dll
    Extracting native library jinput-raw_64.dll
    Extracting native library jinput-wintab.dll
Downloading: text2speech-1.10.3.jar
Downloading: text2speech-1.10.3-natives-windows.jar
    Extracting native library SAPIWrapper_x64.dll
    Extracting native library SAPIWrapper_x86.dll
File: ca.weblite:java-objc-bridge:1.0.0
Skipping due to rules
File: ca.weblite:java-objc-bridge:1.0.0
Skipping due to rules
Downloading: asm-all-5.0.3.jar
Downloading: json-20140107.jar
Downloading: launchwrapper-1.12.jar
Downloading: jna-4.2.1.jar
Downloading: JRift-0.8.0.0.1.jar
Downloading: JMumble-1.11.jar
Downloading: vecmath-1.3.1.jar
Skipping Optifine merge!
Decompiling...
== MCP 9.40 (data: 9.40, client: 1.12.1, server: 1.12.1) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
> Copying jsr305-3.0.1.jar to Libraries
> Copying jsr305-3.0.1-sources.jar to Libraries
!! Missing client jar file. Aborting !!
Traceback (most recent call last):
  File "install.py", line 661, in <module>
    main(os.path.abspath(mcp_version))
  File "install.py", line 525, in main
    shutil.copytree( src_dir, org_src_dir )
  File "C:\Python27\lib\shutil.py", line 185, in copytree
    names = os.listdir(src)
WindowsError: [Error 3] : 'C:\\temp\\vc\\Vivecraft_112-1.12.1-jrbudda-3\\mcp940\\src\\minecraft/*.*'
C:\temp\vc\Vivecraft_112-1.12.1-jrbudda-3>```

OK, there is something I don't know. I tried to just replace KatVR's dll, `WalkerBase.dll`, since there's only five C function in them. Success! Almost. Now while character is in the air, speed multiplies by some value.

I suspect problem is in file
https://github.com/jrbudda/Vivecraft_112/blob/c7db27e017675855d711b2097c1b932522b6e45a/patches/net/minecraft/client/entity/EntityPlayerSP.java.patch

in line 822
`if(this.capabilities.isFlying) yAdd = 5f; //HACK`

but I'm not sure. Maybe it's has something to do with friction.
At least with normal controller movement everything is normal.

So, how can I actually get a working work environment?

**Comment by jrbudda** [comment]
I would recommend using the 1.7.10 repo and getting it working there. The instructions on that repo work. Once you have a working example of talking to your device I can help you port that code into newer versions.

**Comment by topin89** [comment]
OK, thanks.
