### ISSUE TITLE
java.lang.NoClassDefFoundError: cen

### ISSUE THREAD

**Issue by Ectoniqua** [jrbudda/Vivecraft_112#157]
So I was trying to play minecraft with some mods but i kept getting this crash. I tried to remove mods but it didn't work so I figured that it was optifine. Any way to fix this? I tried other versions of optifine too but it did not work.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ModTweaker (Patcher-1.3 (1.8.9).jar)
  Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/20/20 9:59 PM
Description: Initializing game

java.lang.NoClassDefFoundError: cen
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at net.minecraftforge.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:277)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at net.minecraftforge.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:277)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: []
	Minecraft Version: 1.8.9
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 521469880 bytes (497 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
ModTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  net.canelex.perspectivemod.asm.CameraTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.0.0 - Build 9.18.10.3224, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: FurfSky+ Release 1.7.1 - Compatibility.zip, x16 Clear Glass 1.7-1.8.zip, §1§lDungeons Pack.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz

**Comment by jrbudda** [comment]
the fact that all the mods say 1.8.9 is highly suspicious.

**Comment by Ectoniqua** [comment]
wdym. i play on 1.8.9. these mods are for a server.

**Comment by TropheusJ** [comment]
This isn’t even vivecraft

**Comment by Ectoniqua** [comment]
> This isn’t even vivecraft

sorry, i was trying to search this problem and jrbudda's comment came up. i really dont know how github works sorry
