### ISSUE TITLE
java.lang.NoSuchMethodError with CubicChunks 1.12.2

### ISSUE THREAD

**Issue by bixxly** [jrbudda/Vivecraft_112#175]
Game doesn't load into title screen at all. May be a typo given it says "net.minecraft.client.renderer.EntityRenderer.isInMenuRoom()Z".

Crash dump is below

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/25/21 4:49 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.client.renderer.EntityRenderer.isInMenuRoom()Z
	at org.vivecraft.gameplay.screenhandlers.GuiHandler.onGuiScreenChanged(GuiHandler.java:403)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1403)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:869)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:629)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.vivecraft.gameplay.screenhandlers.GuiHandler.onGuiScreenChanged(GuiHandler.java:403)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1403)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:869)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:629)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3825714232 bytes (3648 MB) / 4238868480 bytes (4042 MB) up to 4238868480 bytes (4042 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                    | Source                                          | Signature                                |
	|:------ |:----------------- |:-------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                     | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp               | 9.42                       | minecraft.jar                                   | None                                     |
	| LCHIJA | FML               | 8.0.99.99                  | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854               | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cubicchunkscore   | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None                                     |
	| LCHIJA | mercurius_updater | 1.0                        | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| LCHIJA | cubicchunks       | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None                                     |
	| LCHIJA | cubicgen          | 1.12.2-0.0.115.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | terra121          | 0.1                        | terra121-0.1.jar                                | None                                     |

	Loaded coremods (and transformers): 
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14758 Compatibility Profile Context 21.2.1 27.20.14533.1000' Renderer: 'Radeon RX 580 Series'
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: vivecraft-1.12.2-jrbudda-11-r4-forge
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.14758 Compatibility Profile Context 21.2.1 27.20.14533.1000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.2.1 27.20.14533.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12`

**Comment by Espergium** [comment]
Cubic chunks is not compatible with vivecraft.

**Comment by bixxly** [comment]
Indeed, it wasn't on the incompatible list so I was adding a report to here so it may be added.
