### ISSUE TITLE
Couldn't download vivecraft files

### ISSUE THREAD

**Issue by m4xx1m** [jrbudda/Vivecraft_112#196]
java.io.IOException: expected 200 response; got 301

```
[DownloaderThread] Failed to download: http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar

java.io.IOException: expected 200 response; got 301
	at ru.turikhay.tlauncher.downloader.DownloaderThread.downloadURL(DownloaderThread.java:256)
	at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:184)
	at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:110)
```

**Comment by Techjar** [comment]
TLauncher is not supported. Use Mojang or MultiMC.
