### ISSUE TITLE
FluidLogged Support and Compability

### ISSUE THREAD

**Issue by TheMobC** [jrbudda/Vivecraft_112#206]
I've been trying to go on my favourite 1.12.2 modded server, but it has FluidLogged
FluidLogged makes the game crash at launch with the "Exit Code: 1" error message. I've looked for a solution but I didn't find anything

To recreate:
1: Launch ViveCraft with FluidLogged in .mods
2: Exit Code: 1

I will cry, thanks

**Comment by Techjar** [comment]
Please upload the full log.

**Comment by TheMobC** [comment]
https://pastes.io/hwwm8142dl

i pasted the latest.log file

**Comment by TheMobC** [comment]
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/12805897/latest.log)

**Comment by InuYasha86000** [comment]
I would like to confirm this as I would have a standing crash with to window appearing, once I removed fluidlogged API my modpack worked.

here is the error from the log:

here's the error on 1.12.2:

[01:59:45] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:157) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items
	at net.minecraft.potion.PotionHelper.func_185207_a(PotionHelper.java:154) ~[akh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:518) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:605) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(Main.java:129) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153) ~[VivecraftMain.class:?]
	... 6 more
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[01:59:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I now have the full log
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/12841416/latest.log)
