### ISSUE TITLE
Unable to start the game, unknown error

### ISSUE THREAD

**Issue by zwn007** [jrbudda/Vivecraft_112#210]
I only added one mod, Vivecraft，But the game still shows errors, I've tried multiple versions of forge, all with the same problem.
This is my latest.log

[17:36:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:36:42] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:36:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:36:42] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[17:36:42] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_291, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jdk1.8.0_291\jre
[17:36:43] [main/INFO] [FML]: Searching C:\Users\30528\AppData\Roaming\.minecraft\versions\1.12.2-Forge_14.23.5.2859\mods for mods
[17:36:43] [main/INFO] [FML]: Loading tweaker com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker from vivecraft-1.12.2-jrbudda-NONVR-11-r5-installer.jar
[17:36:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:36:43] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
[17:36:43] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_291]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:103)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Runtime.exit(Runtime.java:107)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.System.exit(System.java:971)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:36:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 6 more

[debug.log](https://github.com/user-attachments/files/18092783/debug.log)
[latest.log](https://github.com/user-attachments/files/18092785/latest.log)

**Comment by fayer3** [comment]
vivecraft for 1.12 is an installer, you can't just drop it into the mods folder
