### ISSUE TITLE
GLSL 3.30 not supported

### ISSUE THREAD

**Issue by Zamundaaa** [jrbudda/Vivecraft_112#65]
I'm on (K)Ubuntu 18.04. The launcher itself crashes like every 3 out of 4 times due to some X-Server error (could be my fault), but when it runs and I start Vivecraft it crashes with the following error:

[19:14:06] [main/INFO]: [STDERR]: java.lang.RuntimeException: Error creating shader: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

[19:14:06] [main/INFO]: [STDERR]: 	at com.mtbs3d.minecrift.render.ShaderHelper.createShader(ShaderHelper.java:27)
[19:14:06] [main/INFO]: [STDERR]: 	at com.mtbs3d.minecrift.render.ShaderHelper.initShaders(ShaderHelper.java:63)
[19:14:06] [main/INFO]: [STDERR]: 	at com.mtbs3d.minecrift.render.VRShaders.setupDepthMask(VRShaders.java:89)
[19:14:06] [main/INFO]: [STDERR]: 	at bib.setupRenderConfiguration(Minecraft.java:4846)
[19:14:06] [main/INFO]: [STDERR]: 	at bib.az(Minecraft.java:1551)
[19:14:06] [main/INFO]: [STDERR]: 	at bib.a(Minecraft.java:669)
[19:14:06] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:129)
[19:14:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:06] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:06] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:06] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:14:06] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:14:06] [main/INFO]: [STDOUT]: Failed to validate depth mask shader!

The issue is that I'm using a RX 580 with the latest mesa drivers from padoka ppa, so I have support for OpenGL 4.5 (glxinfo confirmed and other games run well)...

**Comment by Techjar** [comment]
Hmm, that shader is supposed to just gracefully fail and continue on. Can you show me your glxinfo output?

**Comment by Zamundaaa** [comment]
here it is: https://gist.github.com/Zamundaaa/8fc51ff64494a94d59d1c4a25e436e4a

**Comment by Techjar** [comment]
This seems to be a Mesa limitation, it only supports OpenGL >3.0 if you specifically request a Core context, which we can't do as Minecraft relies on a lot of older API features. That shader is supposed to not crash though, but I guess we didn't push that build. Here: https://cdn.discordapp.com/attachments/194213677560365056/473952433643454484/vivecraft-1.12.2-jrbudda-7-r6-installer.exe

**Comment by Zamundaaa** [comment]
Boots up fine now. Thanks!
