### ISSUE TITLE
Crash while world loads

### ISSUE THREAD

**Issue by Flashfiresfury** [jrbudda/Vivecraft_112#89]
crash-2019-01-06_07.43.38-server.txt
Lasted long enough to move the controller a bit (about 3 seconds)

the galacticraft update def helped

_Originally posted by @Flashfiresfury in https://github.com/jrbudda/Vivecraft_112/issue_comments#issuecomment-451738947_

**Comment by Flashfiresfury** [comment]
Best i can tell, its related to trying to spawn mobs in the world

**Comment by Flashfiresfury** [comment]
Have a repeatable error when i launch now... i can walk around a bit sometimes, throws the same crashing error though
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:335)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:202)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Techjar** [comment]
Looks like yet another issue caused by a mod and not us. Is there any "caused by" in the stack trace?

**Comment by Techjar** [comment]
You don't, it's hard-coded into Vivecraft.

**Comment by jrbudda** [comment]
optifine e3 is included in the latest releases of 1.12.2
